yatube/api/urls.py
from django.urls import path, include
from rest_framework.authtoken import views as auth
from rest_framework.routers import DefaultRouter

from .views import PostViewSet, GroupViewSet, CommentViewSet

router = DefaultRouter()
router.register(r'posts', PostViewSet, basename='posts')
router.register(r'posts/(?P<post_id>\d+)/comments', CommentViewSet,
                basename='comments')
router.register(r'groups', GroupViewSet, basename='groups')

urlpatterns = [
    path('v1/api-token-auth/', auth.obtain_auth_token, name='authtoken'),
    path('v1/', include(router.urls), name='router_v1')
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path(
        '',
        views.index,
        name='index'
    ),
    path(
        'group/<slug:slug>/',
        views.group_posts,
        name='group_list'
    ),
    path(
        'profile/<str:username>/',
        views.profile,
        name='profile'
    ),
    path(
        'posts/<int:post_id>/',
        views.post_detail,
        name='post_detail',
    ),
    path(
        'create/',
        views.post_create,
        name='post_create'
    ),
    path(
        'posts/<int:post_id>/edit/',
        views.post_edit,
        name='post_edit'
    ),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment,
        name='add_comment'
    ),
    path(
        'follow/',
        views.follow_index,
        name='follow_index'
    ),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls', namespace='users')),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('api/', include('api.urls')),
]

handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

    urlpatterns += (path('__debug__/', include(debug_toolbar.urls)),)

yatube/templates/includes/footer.html
<div class="footer-copyright text-center py-3">
  © {% now "Y" %} Copyright
  <p>
    <span style="color:red">Marlo</span>Tube
  </p>
</div>

yatube/templates/includes/forms.html
{% load user_filters %}
{% if form.errors %}
  {% for field in form %}
    {% for error in field.errors %}
      <div class="alert alert-danger">
        {{ error|escape }}
      </div>
    {% endfor %}
  {% endfor %}
  {% for error in form.non_field_errors %}
    <div class="alert alert-danger">
      {{ error|escape }}
    </div>
  {% endfor %}
{% endif %}
<form method="post"
  {% if photo %}
    enctype="multipart/form-data"
  {% endif %}
>
{% csrf_token %}

{% for field in form %}
  <div class="form-group row my-3"
    {% if field.field.required %}
      aria-required="true"
    {% else %}
      aria-required="false"
    {% endif %}
  >
    <label for="{{ field.id_for_label }}">
      {{ field.label }}
        {% if field.field.required %}
          <span class="required text-danger">*</span>
        {% endif %}
    </label>
    <div>
    {{ field|addclass:'form-control' }}
      {% if field.help_text %}
        <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
          {{ field.help_text|safe }}
        </small>
      {% endif %}
    </div>
  </div>
{% endfor %}

yatube/templates/includes/header.html
{% load static %}
{% with request.resolver_match.view_name as view_name %}
  <nav class="navbar navbar-light" style="background-color: lightskyblue">
    <div class="container">
      <a class="navbar-brand
        {% if view_name == 'posts:index' %}
          active
        {% endif %}"
        href="{% url 'posts:index' %}"
      >
        <img src="{% static 'img/logo.png' %}"
          width="30"
          height="30"
          class="d-inline-block align-top"
          alt="Здесь должно было быть лого(тык)"
        >
        <span style="color:red">Marlo</span>Tube
      </a>
      <ul class="nav nav-pills">
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'about:author' %}
              active
            {% endif %}"
            href="{% url 'about:author' %}"
          >Об авторе</a>
        </li>
        <li class="nav-item">
          <a class="nav-link
            {% if view_name  == 'about:tech' %}
              active
            {% endif %}"
            href="{% url 'about:tech' %}"
          >Технологии</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link
            {% if view_name == 'post_create' %}
              active
            {% endif %}"
            href="{% url 'posts:post_create' %}"
          >Новая запись</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light
            {% if view_name  == 'users:password_change_form' %}
              active
            {% endif %}"
            href="{% url 'users:password_change_form' %}"
          >Изменить пароль</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light
            {% if view_name  == 'users:logout' %}
              active
            {% endif %}"
            href="{% url 'users:logout' %}"
          >Выйти</a>
        </li>
        <li>
          Пользователь: {{ user.username }}
        <li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link link-light
            {% if view_name  == 'users:login' %}
              active
            {% endif %}"
            href="{% url 'users:login' %}"
          >Войти</a>
        </li>
        <li class="nav-item">
          <a class="nav-link link-light
            {% if view_name  == 'users:signup' %}
              active
            {% endif %}"
            href="{% url 'users:signup' %}"
          >Регистрация</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>
{% endwith %}